import { Noto_Sans_Devanagari } from "next/font/google";
import "./globals.css";
import AudioPlayer from "./Components/AudioPlayer";

const notoSansDevanagari = Noto_Sans_Devanagari({
  subsets: ["devanagari"],
  weight: ["400", "700"],
  variable: "--font-noto-sans-devanagari",
});

export const metadata = {
  title: "तलासरी सहाय्यक",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansDevanagari.variable} font-krutika antialiased`}>
        {children}
        <AudioPlayer /> {/* 🔊 Global background music */}
      </body>
    </html>
  );
}
